# Generated by Django 2.2.7 on 2019-12-13 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_prod_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_prod_info', to='warehouse.Product')),
                ('old_prod_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_prod_info', to='warehouse.Product')),
            ],
        ),
    ]
