# Generated by Django 2.2.7 on 2019-12-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_fullproductinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullproductinfo',
            name='new_prod_info',
        ),
        migrations.RemoveField(
            model_name='fullproductinfo',
            name='old_prod_info',
        ),
        migrations.AddField(
            model_name='fullproductinfo',
            name='prod_info',
            field=models.ManyToManyField(related_name='new_prod_info', to='warehouse.Product'),
        ),
    ]
