# Generated by Django 2.2.7 on 2019-12-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20191213_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_man_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_model_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='price_ts',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
