# Generated by Django 2.2.7 on 2019-12-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20191216_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_ts',
            field=models.FloatField(default=0),
        ),
    ]
