# Generated by Django 2.2.7 on 2019-12-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_productdiff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
